version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"

  myapp: 
    build: . 
    depends_on:
      - redis
      - rabbitmq
      - keycloak
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOSTNAME=redis
      - RABBITMQ_HOSTNAME=rabbitmq

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: "postgres_user"  # Burayı istediğiniz kullanıcı adıyla değiştirin
      POSTGRES_PASSWORD: "postgres_password"  # Burayı güvenli bir şifreyle değiştirin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
